---
site_name: Docs Template
site_description: >-
  Tutorial on using documentation as code.
site_url: https://robinmordasiewicz.github.io/docs-template/
site_author: Robin Mordasiewicz

repo_name: "robinmordasiewicz/docs-template"
repo_url: https://github.com/robinmordasiewicz/docs-template/
edit_uri: edit/main/docs/

# yamllint disable-line rule:line-length
copyright: "Try to be nice."

extra:
  annotate:
    json: [.s2]
  generator: false
  social:
    - icon: custom/fc-lib-facebook
      link: https://www.facebook.com/Fortinet/
    - icon: custom/fc-lib-twitter
      link: https://x.com/Fortinet
    - icon: custom/fc-lib-youtube
      link: https://www.youtube.com/@fortinet
    - icon: custom/fc-lib-linkedin
      link: https://www.linkedin.com/company/fortinet

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra_css: [extra.css]
# extra_javascript: [extra.js]

theme:
  name: material
  include_sidebar: false
  logo: logo.svg
  favicon: favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.footer
    # - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: grey
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      accent: black
      scheme: slate
      toggle:
        icon: material/toggle-switch
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: "!!python/name:material.extensions.emoji.twemoji"
      emoji_generator: "!!python/name:material.extensions.emoji.to_svg"
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      toc_depth: "1-1"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: robinmordasiewicz
      repo: devops-toolkit
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: "!!python/object/apply:pymdownx.slugs.slugify"
      kwds:
        case: lower

plugins:
  - glightbox
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
